- hosts: gpus
  become: true
  become_user: root
  roles:
    - { role: base }
    - { role: anaconda }
    - { role: docker-ce, docker_version: 18.09.0 }
    - { role: cuda, cuda_version_major: 10, cuda_version_minor: 0 }
    - { role: cudnn, cuda_version_major: 10, cuda_version_minor: 0, cudnn_version: 7.3 }
    - { role: nvidia-docker, nvidia_docker_version: 2.0.3 }
