---
# Setup task.
# eg: tasks/setup-Ubuntu.yml
- include_tasks: "disable-unattended-update-{{ ansible_distribution }}.yml"
- include_tasks: "clean-apt-cache.yml"
- include_tasks: "setup-locale-{{ ansible_distribution }}.yml"
- include_tasks: "setup-{{ ansible_distribution }}.yml"
