---
- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: present

- name:
  shell: "sudo add-apt-repository universe"

- name:
  shell: "sudo apt update"

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install main apt packages
  apt: name={{item}} state=latest
  with_items:
    - htop
    - tmux
    - vim
    - neovim
    - curl
    - wget
    - git
    - zip
    - unzip
    - rsync
    - iotop
    - iftop
    - unzip
    - python3-pip
    - jq
    - ncdu
    - nfs-common
    - httpie
    - awscli
    - ranger
    - extundelete

- name: Install main pip packages
  pip: name={{item}} state=latest
  with_items:
    - pip
    - ansible
    - jmespath
    - docker
    - docker-compose
