---
- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: present

- name:
  shell: "sudo add-apt-repository universe"

- name:
  shell: "sudo apt update"

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install docker-py
  pip:
    name: pip
    state: latest

- name: Install docker
  pip:
    name: docker
    state: present

- name: Install pyOpenSSL
  pip:
    name: pyOpenSSL
    state: present

- name: Install Ansible
  pip:
    name: ansible
    state: present

- name: Install jmespath
  pip:
    name: jmespath
    state: present

- name: Install apache-libcloud
  pip:
    name: apache-libcloud
    state: present

- name: Install jq
  apt:
    name: jq
    state: present

- name: Install git
  apt:
    name: git
    state: present

- name: Install htop
  apt:
    name: htop
    state: present

- name: Install tmux
  apt:
    name: tmux
    state: present

- name: Install zip
  apt:
    name: zip
    state: present

- name: Install unzip
  apt:
    name: unzip
    state: present

- name: Install rsync
  apt:
    name: rsync
    state: present

- name: Install Silver Searcher
  apt:
    name: silversearcher-ag
    state: present

- name: Install sysdig
  apt:
    name: sysdig
    state: present

- name: Install ncdu
  apt:
    name: ncdu
    state: present

- name: Install nfs-common
  apt:
    name: nfs-common
    state: present

- name: Install httpie
  apt:
    name: httpie
    state: present

- name: Install docker-compose
  pip:
    name: docker-compose
    state: present

- name: Install openjdk-8-jre
  apt:
    name: openjdk-8-jre
    state: present
